[package]
name = "lib-col"
version = "0.4.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
hecs = { workspace = true }
hashbrown = { workspace = true }
glam = { workspace = true }

[dev-dependencies]
rand = "0.9.1"
svg = "0.18.0"