[package]
name = "lib-asset"
version = "0.3.0"
edition = "2024"

[dependencies]
log = { workspace = true }
anyhow = { workspace = true }
strum = { workspace = true }
hashbrown = { workspace = true, features = ["serde"] }
serde = { version = "1", features = ["derive"] }
macroquad = { workspace = true }
lib-col = { path = "../lib-col" }

[target.'cfg(target_family = "wasm")'.dependencies]
postcard = "1"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
thiserror = "2"
postcard = { version = "1", features = ["use-std"] }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
tiled = { version = "0.14.0", default-features = false, features = [] }
