[package]
name = "lib-asset"
version = "0.7.2"
edition = "2024"

[[bin]]
name = "asset-compiler"
path = "tool/main.rs"

[dependencies]
glam = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
strum = { workspace = true }
hashbrown = { workspace = true, features = ["serde"] }
serde = { version = "1", features = ["derive"] }
macroquad = { workspace = true }
lib-col = { path = "../lib-col" }
thiserror = "2"
postcard = "1"
clap = { version = "4", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
tiled = { version = "0.14.0", default-features = false, features = [], optional = true }

[features]
dbg = ["dep:serde_json"]
dev-env = ["dep:clap", "dep:tiled", "postcard/use-std", "dbg"]
